Repository Watkins7/pickup_game_447, pull requests merged in 2022-04, with the labels that each got.

#50 Added Model for storing Timeslots and associated tests.
  pick_up_app/models.py
  pick_up_app/tests_model.py
Labels: enhancement

#54 Implemented autofill team search bar
  pick_up_app/templates/pick_up_app/home_page.html
  pick_up_app/templates/pick_up_app/index.html
  pick_up_app/templates/pick_up_app/team_search.html
  pick_up_app/urls.py
  pick_up_app/views.py
Labels: enhancement

#64 Features/nick user
  pick_up_app/forms.py
  pick_up_app/models.py
  pick_up_app/templates/pick_up_app/home_page.html
  pick_up_app/test_selenium.py
  pick_up_app/tests_model.py
  pick_up_app/urls.py
  pick_up_app/views.py
Labels: bug

#65 Implements a working redirection calendar
  pick_up_app/forms.py
  pick_up_app/models.py
  pick_up_app/static/css/stylecalendar.css
  pick_up_app/static/css/styletimeslot.css
  pick_up_app/templates/pick_up_app/calendar.html
  pick_up_app/templates/pick_up_app/timeslot.html
  pick_up_app/test_form.py
  pick_up_app/test_selenium.py
  pick_up_app/urls.py
  pick_up_app/utils.py
  pick_up_app/views.py
Labels: enhancement

#66 Feature/nick search bar tests
  pick_up_app/templates/pick_up_app/home_page.html
  pick_up_app/templates/pick_up_app/team_search.html
  pick_up_app/test_selenium.py
Labels: documentation
